// src/pages/chordDiagram/index.vue
<template>
  <div>
    ChordDiagram组件测试
    <div class="comp_container"></div>
  </div>
</template>

<script setup lang="ts">
// 组件逻辑
import { onMounted } from 'vue';
import ChordDiagram from '../../../lib/chordDiagram/chordDiagram';

onMounted(() => {
  new ChordDiagram('asd','asd',document.getElementsByClassName('comp_container')[0], 0, {})
})
</script>

<style scoped>
/* 添加样式 */
</style>

// src/pages/chordDiagram/index.tsx
import React, { useEffect, useRef } from "react";
import ChordDiagram from "../../../lib/chordDiagram/chordDiagram";

const ChordDiagramTest: React.FC = () => {
  const compContainerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (compContainerRef.current) {
      new ChordDiagram("asd", "asd", compContainerRef.current, 0, {});
    }
  }, []);

  return (
    <div>
      ChordDiagram组件测试
      <div className="comp_container" ref={compContainerRef}></div>
    </div>
  );
};

export default ChordDiagramTest;
