// src/pages/imageView/index.vue
<template>
  <div>
    ImageView组件测试
    <div class="comp_container"></div>
  </div>
</template>

<script setup lang="ts">
// 组件逻辑
import { onMounted } from 'vue';
import ImageView from '../../../lib/imageView/imageView';

onMounted(() => {
  new ImageView('asd','asd',document.getElementsByClassName('comp_container')[0], 0, {})
})
</script>

<style scoped>
/* 添加样式 */
</style>

// src/pages/imageView/index.tsx
import React, { useEffect, useRef } from "react";
import ImageView from "../../../lib/imageView/imageView";

const ChordDiagramTest: React.FC = () => {
  const compContainerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (compContainerRef.current) {
      new ImageView("asd", "asd", compContainerRef.current, 0, {});
    }
  }, []);

  return (
    <div>
      ImageView组件测试
      <div className="comp_container" ref={compContainerRef}></div>
    </div>
  );
};

export default ChordDiagramTest;
