// src/components/InputNumber.vue
<template>
  <input type="number" v-model.number="value" :step="props.propertyDic.type === 'double' ? 0.01 : 1" @change="updateValue" />
</template>

<script setup lang="ts">
  import { ref, watch } from "vue";
  import { defineProps, defineEmits } from "vue";
  import { PropertyDictionaryItem } from "lib/types/property";

  const props = defineProps<{ modelValue: number; propertyDic: PropertyDictionaryItem }>();
  const emit = defineEmits(["update:modelValue"]);

  const value = ref(props.modelValue);

  watch(
    () => props.modelValue,
    (newValue) => {
      value.value = newValue;
    }
  );

  const updateValue = () => {
    emit("update:modelValue", value.value);
  };
</script>

// src/components/InputNumber.tsx
import React, { useState, useEffect } from "react";
import { PropertyDictionaryItem } from "lib/types/property";

interface Props {
  propertyValue: number;
  propertyDic: PropertyDictionaryItem;
  onUpdatePropertyValue: (value: number) => void;
}

const NumberInput: React.FC<Props> = ({ propertyValue, propertyDic, onUpdatePropertyValue }) => {
  const [value, setValue] = useState<number>(propertyValue);

  useEffect(() => {
    setValue(propertyValue);
  }, [propertyValue]);

  const updateValue = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = parseFloat(e.target.value);
    setValue(newValue);
    onUpdatePropertyValue(newValue);
  };

  return <input type="number" value={value} step={propertyDic.type === "Double" ? 0.01 : 1} onChange={updateValue} />;
};

export default NumberInput;
