// src/components/PropertyItem.tsx
import React, { useState } from "react";
import InputCheckbox from "./InputCheckbox";
import InputNumber from "./InputNumber";
import InputArray from "./InputArray";
import InputRange from "./InputRange";

import { PropertyDictionaryItem } from "lib/types/property";

interface Props {
  propertyDic: PropertyDictionaryItem;
  propertyValue: any;
  propertyName: string;
  onUpdatePropertyValue: (newValue: any, propertyName: string) => void;
}

const PropertyItem: React.FC<Props> = ({ propertyDic, propertyValue, propertyName, onUpdatePropertyValue }) => {
  const [value, setValue] = useState(propertyValue);

  const getInputComponent = (type: string | undefined): React.ElementType | string => {
    switch (type) {
      case "String":
        return "input";
      case "Boolean":
        return InputCheckbox;
      case "Int":
      case "Double":
        return InputNumber;
      case "DoubleArray":
        return InputArray;
      case "Range":
        return InputRange;
      default:
        return "input";
    }
  };

  const shouldShowField = (field: PropertyDictionaryItem) => {
    return field.show;
  };

  const valueUpdate = (newVal: any) => {
    setValue(newVal);
    onUpdatePropertyValue(newVal, propertyName);
  };

  const InputComponent = getInputComponent(propertyDic.type);

  return (
    shouldShowField(propertyDic) && (
      <div>
        <div>{propertyDic.displayName}</div>
        {typeof InputComponent === "string" ? <input value={value} onChange={(e) => valueUpdate(e.target.value)} disabled={!propertyDic.editable} /> : <InputComponent propertyDic={propertyDic} propertyValue={value} onUpdatePropertyValue={valueUpdate} disabled={!propertyDic.editable} />}
      </div>
    )
  );
};

export default PropertyItem;

// src/components/PropertyItem.vue
<template>
  <div>{{ props.propertyDic.displayName }}</div>
  <component :is="getInputComponent(props.propertyDic.type)" v-model="value" :propertyDic="props.propertyDic" :propertyValue="props.propertyValue" :disabled="!props.propertyDic.editable" v-if="shouldShowField(props.propertyDic)" @update:modelValue="valueUpdate" />
</template>
<script setup lang="ts">
  import InputCheckbox from "./InputCheckbox.vue";
  import InputNumber from "./InputNumber.vue";
  import InputArray from "./InputArray.vue";
  import InputRange from "./InputRange.vue";
  import { ref } from "vue";
  // import { PropertyDictionaryItem } from "lib/types/property";

  interface propInterface {
    propertyDic: any;
    propertyValue: any;
    propertyName: string;
  }

  const props = defineProps<propInterface>();

  const emit = defineEmits(["update:propertyValue"]);

  const value = ref(props.propertyValue);

  defineOptions({
    components: {
      InputCheckbox,
      InputNumber,
      InputArray,
      InputRange,
    },
  });

  const getInputComponent = (type: string | undefined) => {
    switch (type) {
      case "String":
        return "input";
      case "Boolean":
        return "input-checkbox";
      case "Int":
        return "input-number";
      case "Double":
        return "input-number";
      case "DoubleArray":
        return "input-array";
      case "Range":
        return "input-range";
      default:
        return "input";
    }
  };

  const shouldShowField = (field: any) => {
    return field.show;
  };

  const valueUpdate = (newVal: any) => {
    value.value = newVal;
    emit("update:propertyValue", newVal, props.propertyName);
  };
</script>
